ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BIT_CAT_PAIS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE BIT_CAT_PAIS (
    UUID_BITACORA VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
    UUID_PAIS VARCHAR2(36) NOT NULL,
    CODIGO VARCHAR2(3) NOT NULL,
    DESCRIPCION VARCHAR2(255) NOT NULL,
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    ACCION VARCHAR2(15) NOT NULL,
    IP VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_BIT_CAT_PAIS_UUID_BITACORA PRIMARY KEY (UUID_BITACORA)
);

COMMENT ON TABLE BIT_CAT_PAIS IS 'Bitácora de catálogo de países';
COMMENT ON COLUMN BIT_CAT_PAIS.UUID_BITACORA IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN BIT_CAT_PAIS.UUID_PAIS IS 'Identificador único UUID de la tabla CAT_PAIS';
COMMENT ON COLUMN BIT_CAT_PAIS.CODIGO IS 'Código ISO 3166-1 alfa-3 del país';
COMMENT ON COLUMN BIT_CAT_PAIS.DESCRIPCION IS 'Nombre oficial o descripción del país';
COMMENT ON COLUMN BIT_CAT_PAIS.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN BIT_CAT_PAIS.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN BIT_CAT_PAIS.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN BIT_CAT_PAIS.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN BIT_CAT_PAIS.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN BIT_CAT_PAIS.NOTAS IS 'Observaciones adicionales del registro';
COMMENT ON COLUMN BIT_CAT_PAIS.ACCION IS 'Acción ejecutada sobre el registro: INSERT O UPDATE';
COMMENT ON COLUMN BIT_CAT_PAIS.IP IS 'Dirección IP desde donde se realizó la operación';

CREATE OR REPLACE TRIGGER TRG_BIT_CAT_PAIS
AFTER INSERT OR UPDATE ON CAT_PAIS
FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(15);
BEGIN
    IF INSERTING THEN
        V_ACCION := 'INSERT';
    ELSIF UPDATING THEN
        V_ACCION := 'UPDATE';
    END IF;
    INSERT INTO BIT_CAT_PAIS (UUID_PAIS, CODIGO, DESCRIPCION, ESTATUS_REGISTRO, FECHA_CREACION,
                              CREADO_POR, FECHA_ACTUALIZACION, ACTUALIZADO_POR, NOTAS, ACCION, IP)
    VALUES (:NEW.UUID_PAIS,
        :NEW.CODIGO,
        :NEW.DESCRIPCION,
        :NEW.ESTATUS_REGISTRO,
        :NEW.FECHA_CREACION,
        :NEW.CREADO_POR,
        :NEW.FECHA_ACTUALIZACION,
        :NEW.ACTUALIZADO_POR,
        :NEW.NOTAS,
        V_ACCION,
        FN_GET_IP());
end;
/
