ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CAT_TIPO_CLIENTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CAT_TIPO_CLIENTE (
    UUID_TIPO_CLIENTE VARCHAR2(36) NOT NULL,
    CLAVE VARCHAR2(7) NOT NULL ,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(100),
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_CAT_TIPO_CLIENTE_UUID_TIPO_CLIENTE PRIMARY KEY (UUID_TIPO_CLIENTE),
    CONSTRAINT UK_CAT_TIPO_CLIENTE_CLAVE UNIQUE (CLAVE),
    CONSTRAINT CK_CAT_TIPO_CLIENTE_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);

COMMENT ON TABLE CAT_TIPO_CLIENTE IS 'Catálogo de tipos de cliente';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.UUID_TIPO_CLIENTE IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.CLAVE IS 'Clave del tipo de cliente';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.NOMBRE IS 'Nombre del tipo de cliente';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.DESCRIPCION IS 'Descripción del tipo de cliente';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.NOTAS IS 'Observaciones adicionales del registro';
