/*========================================================
  CREAR TABLA CAT_PAIS
========================================================*/
ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CAT_PAIS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CAT_PAIS (
    UUID_PAIS VARCHAR2(36) NOT NULL,
    CODIGO VARCHAR2(3) NOT NULL,
    DESCRIPCION VARCHAR2(255) NOT NULL,
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_CAT_PAIS_UUID_PAIS PRIMARY KEY (UUID_PAIS),
    CONSTRAINT UK_CAT_PAIS_CODIGO UNIQUE (CODIGO),
    CONSTRAINT CK_CAT_PAIS_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);

COMMENT ON TABLE CAT_PAIS IS 'Catálogo de países';
COMMENT ON COLUMN CAT_PAIS.UUID_PAIS IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CAT_PAIS.CODIGO IS 'Código ISO 3166-1 alfa-3 del país';
COMMENT ON COLUMN CAT_PAIS.DESCRIPCION IS 'Nombre oficial o descripción del país';
COMMENT ON COLUMN CAT_PAIS.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CAT_PAIS.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CAT_PAIS.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CAT_PAIS.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CAT_PAIS.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CAT_PAIS.NOTAS IS 'Observaciones adicionales del registro';
