ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CAT_TIPO_TOKEN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CAT_TIPO_TOKEN (
    UUID_TIPO_TOKEN VARCHAR2(36) NOT NULL,
    CLAVE VARCHAR2(7) NOT NULL ,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(100),
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_CAT_TIPO_TOKEN_UUID_TIPO_TOKEN PRIMARY KEY (UUID_TIPO_TOKEN),
    CONSTRAINT UK_CAT_TIPO_TOKEN_CLAVE UNIQUE (CLAVE),
    CONSTRAINT CK_CAT_TIPO_TOKEN_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);

COMMENT ON TABLE CAT_TIPO_TOKEN IS 'Catálogo de tipos de token';
COMMENT ON COLUMN CAT_TIPO_TOKEN.UUID_TIPO_TOKEN IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CAT_TIPO_TOKEN.CLAVE IS 'Clave del tipo de token';
COMMENT ON COLUMN CAT_TIPO_TOKEN.NOMBRE IS 'Nombre del tipo de token';
COMMENT ON COLUMN CAT_TIPO_TOKEN.DESCRIPCION IS 'Descripción del tipo de token';
COMMENT ON COLUMN CAT_TIPO_TOKEN.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CAT_TIPO_TOKEN.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CAT_TIPO_TOKEN.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CAT_TIPO_TOKEN.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CAT_TIPO_TOKEN.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CAT_TIPO_TOKEN.NOTAS IS 'Observaciones adicionales del registro';
