/*========================================================
  CREAR TABLA CAT_CIUDAD
========================================================*/
ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CAT_CIUDAD CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CAT_CIUDAD (
    UUID_CIUDAD VARCHAR2(36)  NOT NULL,
    UUID_ESTADO VARCHAR2(36) NOT NULL,
    DESCRIPCION VARCHAR2(255) NOT NULL,
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_CAT_CIUDAD_UUID_CIUDAD PRIMARY KEY (UUID_CIUDAD),
    CONSTRAINT CK_CAT_CIUDAD_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);

COMMENT ON TABLE CAT_CIUDAD IS 'Catálogo de ciudades';
COMMENT ON COLUMN CAT_CIUDAD.UUID_CIUDAD IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CAT_CIUDAD.UUID_ESTADO IS 'Identificador único UUID del estado al que pertenece la ciudad';
COMMENT ON COLUMN CAT_CIUDAD.DESCRIPCION IS 'Nombre de la ciudad';
COMMENT ON COLUMN CAT_CIUDAD.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CAT_CIUDAD.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CAT_CIUDAD.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CAT_CIUDAD.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CAT_CIUDAD.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CAT_CIUDAD.NOTAS IS 'Observaciones adicionales del registro';
