/*========================================================
  TABLA DE CAT_ESTADO_PAGO
========================================================*/
ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CAT_ESTADO_PAGO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CAT_ESTADO_PAGO (
    UUID_ESTADO_PAGO VARCHAR2(36) NOT NULL,
    CLAVE VARCHAR2(7) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(100),
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_CAT_ESTADO_PAGO_UUID_ESTADO_PAGO PRIMARY KEY (UUID_ESTADO_PAGO),
    CONSTRAINT UK_CAT_ESTADO_PAGO_CLAVE UNIQUE (CLAVE),
    CONSTRAINT CK_CAT_ESTADO_PAGO_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);

COMMENT ON TABLE CAT_ESTADO_PAGO IS 'Catálogo del tipo de estado de pago';
COMMENT ON COLUMN CAT_ESTADO_PAGO.UUID_ESTADO_PAGO IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CAT_ESTADO_PAGO.CLAVE IS 'Clave del estado del pago';
COMMENT ON COLUMN CAT_ESTADO_PAGO.NOMBRE IS 'Nombre del estado del pago';
COMMENT ON COLUMN CAT_ESTADO_PAGO.DESCRIPCION IS 'Descripción del estado del pago';
COMMENT ON COLUMN CAT_ESTADO_PAGO.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CAT_ESTADO_PAGO.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CAT_ESTADO_PAGO.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CAT_ESTADO_PAGO.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CAT_ESTADO_PAGO.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CAT_ESTADO_PAGO.NOTAS IS 'Observaciones adicionales del registro';
