/*========================================================
  TABLA DE CAT_ESTADO_FACTURAS
========================================================*/
ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CAT_ESTADO_FACTURA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CAT_ESTADO_FACTURA (
    UUID_ESTADO_FACTURA VARCHAR2(36) NOT NULL,
    CLAVE VARCHAR2(7) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(100),
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_CAT_ESTADO_FACTURA_UUID_ESTADO_FACTURA PRIMARY KEY (UUID_ESTADO_FACTURA),
    CONSTRAINT UK_CAT_ESTADO_FACTURA_CLAVE UNIQUE (CLAVE),
    CONSTRAINT CK_CAT_ESTADO_FACTURA_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);

COMMENT ON TABLE CAT_ESTADO_FACTURA IS 'Catálogo del tipo de estado de factura';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.UUID_ESTADO_FACTURA IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.CLAVE IS 'Clave del estado de la factura';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.NOMBRE IS 'Nombre del estado de la factura';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.DESCRIPCION IS 'Descripción del estado de la factura';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.NOTAS IS 'Observaciones adicionales del registro';



