/*========================================================
  TABLA DE CAT_ROL
========================================================*/
ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CAT_ROL CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CAT_ROL (
    UUID_ROL VARCHAR2(36) NOT NULL,
    CLAVE VARCHAR2(5) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(100),
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_CAT_ROL_UUID_ROL PRIMARY KEY (UUID_ROL),
    CONSTRAINT UK_CAT_ROL_CLAVE UNIQUE (CLAVE),
    CONSTRAINT CK_CAT_ROL_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);

COMMENT ON TABLE CAT_ROL IS 'Catálogo de roles del sistema';
COMMENT ON COLUMN CAT_ROL.UUID_ROL IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CAT_ROL.CLAVE IS 'Clave del rol';
COMMENT ON COLUMN CAT_ROL.NOMBRE IS 'Nombre del rol';
COMMENT ON COLUMN CAT_ROL.DESCRIPCION IS 'Descripción del rol';
COMMENT ON COLUMN CAT_ROL.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CAT_ROL.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CAT_ROL.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CAT_ROL.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CAT_ROL.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CAT_ROL.NOTAS IS 'Observaciones adicionales del registro';
