/*========================================================
  CREAR TABLA CAT_ESTADO
========================================================*/
ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CAT_ESTADO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CAT_ESTADO (
    UUID_ESTADO VARCHAR2(36) NOT NULL,
    UUID_PAIS VARCHAR2(36) NOT NULL,
    DESCRIPCION VARCHAR2(255) NOT NULL,
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_CAT_ESTADO_UUID_ESTADO PRIMARY KEY (UUID_ESTADO),
    CONSTRAINT CK_CAT_ESTADO_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);

COMMENT ON TABLE CAT_ESTADO IS 'Catálogo de estados';
COMMENT ON COLUMN CAT_ESTADO.UUID_ESTADO IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CAT_ESTADO.UUID_PAIS IS 'Identificador único UUID del país al que pertenece el estado';
COMMENT ON COLUMN CAT_ESTADO.DESCRIPCION IS 'Nombre del estado';
COMMENT ON COLUMN CAT_ESTADO.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CAT_ESTADO.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CAT_ESTADO.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CAT_ESTADO.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CAT_ESTADO.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CAT_ESTADO.NOTAS IS 'Observaciones adicionales del registro';
