ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CAT_ESTADO_MENSAJE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CAT_ESTADO_MENSAJE(
    UUID_ESTADO_MENSAJE VARCHAR2(36) NOT NULL,
    CLAVE VARCHAR2(7) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(100),
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_CAT_ESTADO_MENSAJE_UUID_ESTADO_MENSAJE PRIMARY KEY (UUID_ESTADO_MENSAJE),
    CONSTRAINT UK_CAT_ESTADO_MENSAJE_CLAVE UNIQUE (CLAVE),
    CONSTRAINT CK_CAT_ESTADO_MENSAJE_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);

COMMENT ON TABLE CAT_ESTADO_MENSAJE IS 'Catálogo de estados de mensajes';
COMMENT ON COLUMN CAT_ESTADO_MENSAJE.UUID_ESTADO_MENSAJE IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CAT_ESTADO_MENSAJE.CLAVE IS 'Clave del estado del mensaje';
COMMENT ON COLUMN CAT_ESTADO_MENSAJE.NOMBRE IS 'Nombre del estado del mensaje';
COMMENT ON COLUMN CAT_ESTADO_MENSAJE.DESCRIPCION IS 'Descripción del estado del mensaje';
COMMENT ON COLUMN CAT_ESTADO_MENSAJE.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CAT_ESTADO_MENSAJE.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CAT_ESTADO_MENSAJE.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CAT_ESTADO_MENSAJE.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CAT_ESTADO_MENSAJE.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CAT_ESTADO_MENSAJE.NOTAS IS 'Observaciones adicionales del registro';
