ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CUR_USUARIO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CUR_USUARIO (
    UUID_USUARIO VARCHAR2(36) NOT NULL,
    UUID_PERSONA VARCHAR2(36) NOT NULL,
    UUID_ROL VARCHAR2(36) NOT NULL,
    PASSWORD_HASH VARCHAR2(600) NOT NULL,
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_CUR_USUARIO_UUID_USUARIO PRIMARY KEY (UUID_USUARIO),
    CONSTRAINT UK_CUR_USUARIO_UUID_PERSONA UNIQUE (UUID_PERSONA),
    CONSTRAINT CK_CUR_USUARIO_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);

COMMENT ON TABLE CUR_USUARIO IS 'Tabla que contiene los datos de los usuarios del sistema';
COMMENT ON COLUMN CUR_USUARIO.UUID_USUARIO IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CUR_USUARIO.UUID_PERSONA IS 'Identificador único UUID de la tabla CUR_PERSONA';
COMMENT ON COLUMN CUR_USUARIO.UUID_ROL IS 'Identificador único UUID de la tabla CAT_ROL';
COMMENT ON COLUMN CUR_USUARIO.PASSWORD_HASH IS 'Hash de la contraseña del usuario';
COMMENT ON COLUMN CUR_USUARIO.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CUR_USUARIO.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CUR_USUARIO.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CUR_USUARIO.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CUR_USUARIO.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CUR_USUARIO.NOTAS IS 'Observaciones adicionales del registro';
