ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CUR_TOKEN_VERIFICACION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CUR_TOKEN_VERIFICACION (
    UUID_TOKEN_VERIFICACION VARCHAR2(36) NOT NULL,
    UUID_PERSONA VARCHAR2(36) NOT NULL,
    UUID_TIPO_TOKEN VARCHAR2(36) NOT NULL,
    TOKEN VARCHAR2(600) NOT NULL,
    USADO NUMBER(1) DEFAULT 0 NOT NULL,
    CADUCADO NUMBER(1) DEFAULT 0 NOT NULL,
    FECHA_ALTA TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_EXPIRACION TIMESTAMP NOT NULL,
    FECHA_USO TIMESTAMP,
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_CUR_TOKEN_VERIFICACION_UUID_TOKEN_VERIFICACION PRIMARY KEY (UUID_TOKEN_VERIFICACION),
    CONSTRAINT UK_CUR_TOKEN_VERIFICACION_TOKEN UNIQUE (TOKEN),
    CONSTRAINT CK_CUR_TOKEN_VERIFICACION_USADO CHECK (USADO IN (0,1)),
    CONSTRAINT CK_CUR_TOKEN_VERIFICACION_CADUCADO CHECK (CADUCADO IN (0,1)),
    CONSTRAINT CK_CUR_TOKEN_VERIFICACION_FECHA_EXPIRACION_FECHA_ALTA CHECK (FECHA_EXPIRACION > FECHA_ALTA),
    CONSTRAINT CK_CUR_TOKEN_VERIFICACION_FECHA_USO_FECHA_ALTA CHECK (FECHA_USO IS NULL OR FECHA_USO >= FECHA_ALTA),
    CONSTRAINT CK_CUR_TOKEN_VERIFICACION_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);

COMMENT ON TABLE CUR_TOKEN_VERIFICACION IS 'Tabla que contiene los tokens de verificación';
COMMENT ON COLUMN CUR_TOKEN_VERIFICACION.UUID_TOKEN_VERIFICACION IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CUR_TOKEN_VERIFICACION.UUID_PERSONA IS 'Identificador único UUID de la tabla CUR_PERSONA';
COMMENT ON COLUMN CUR_TOKEN_VERIFICACION.UUID_TIPO_TOKEN IS 'Identificador único UUID de la tabla CAT_TIPO_TOKEN';
COMMENT ON COLUMN CUR_TOKEN_VERIFICACION.TOKEN IS 'Token de verificación';
COMMENT ON COLUMN CUR_TOKEN_VERIFICACION.USADO IS 'Indica si el token ya fue usado';
COMMENT ON COLUMN CUR_TOKEN_VERIFICACION.CADUCADO IS 'Indica si el token ya fue caducado';
COMMENT ON COLUMN CUR_TOKEN_VERIFICACION.FECHA_ALTA IS 'Fecha de creación del token';
COMMENT ON COLUMN CUR_TOKEN_VERIFICACION.FECHA_EXPIRACION IS 'Fecha de expiración del token';
COMMENT ON COLUMN CUR_TOKEN_VERIFICACION.FECHA_USO IS 'Fecha de uso del token';
COMMENT ON COLUMN CUR_TOKEN_VERIFICACION.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CUR_TOKEN_VERIFICACION.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CUR_TOKEN_VERIFICACION.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CUR_TOKEN_VERIFICACION.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CUR_TOKEN_VERIFICACION.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CUR_TOKEN_VERIFICACION.NOTAS IS 'Observaciones adicionales del registro';
