ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CUR_MENSAJE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CUR_MENSAJE (
    UUID_MENSAJE VARCHAR2(36) NOT NULL,
    UUID_ESTADO_MENSAJE VARCHAR2(36) NOT NULL,
    UUID_CLIENTE VARCHAR2(36) NOT NULL,
    DESCRIPCION VARCHAR2(1000) NOT NULL,
    FECHA_ENVIO DATE DEFAULT SYSDATE NOT NULL,
    RESPUESTA VARCHAR2(1000),
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_CUR_MENSAJE_UUID_MENSAJE PRIMARY KEY (UUID_MENSAJE),
    CONSTRAINT CK_CUR_MENSAJE_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);

COMMENT ON TABLE CUR_MENSAJE IS 'Tabla que contiene los mensajes de contacto';
COMMENT ON COLUMN CUR_MENSAJE.UUID_MENSAJE IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CUR_MENSAJE.UUID_ESTADO_MENSAJE IS 'Identificador único UUID de la tabla CAT_ESTADO_MENSAJE';
COMMENT ON COLUMN CUR_MENSAJE.UUID_CLIENTE IS 'Identificador único UUID de la tabla CUR_CLIENTE';
COMMENT ON COLUMN CUR_MENSAJE.DESCRIPCION IS 'Descripción del mensaje';
COMMENT ON COLUMN CUR_MENSAJE.FECHA_ENVIO IS 'Fecha de envío del mensaje';
COMMENT ON COLUMN CUR_MENSAJE.RESPUESTA IS 'Respuesta proporcionada al mensaje';
COMMENT ON COLUMN CUR_MENSAJE.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CUR_MENSAJE.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CUR_MENSAJE.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CUR_MENSAJE.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CUR_MENSAJE.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CUR_MENSAJE.NOTAS IS 'Observaciones adicionales del registro';
