ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CUR_PERSONA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CUR_PERSONA (
    UUID_PERSONA VARCHAR2(36) NOT NULL,
    UUID_CIUDAD VARCHAR2(36)  NOT NULL,
    UUID_ESTADO VARCHAR2(36) NOT NULL,
    UUID_PAIS VARCHAR2(36) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(50) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(50),
    TELEFONO VARCHAR2(20),
    EMAIL VARCHAR2(100) NOT NULL,
    FECHA_ALTA DATE DEFAULT SYSDATE NOT NULL,
    VERIFICADO NUMBER(2) DEFAULT 99 NOT NULL,
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_CUR_PERSONA_UUID_PERSONA PRIMARY KEY (UUID_PERSONA),
    CONSTRAINT UK_CUR_PERSONA_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_CUR_PERSONA_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99)),
    CONSTRAINT CK_CUR_PERSONA_VERIFICADO CHECK (VERIFICADO IN (0, 99))
);

COMMENT ON TABLE CUR_PERSONA IS 'Tabla que almacena información de la persona';
COMMENT ON COLUMN CUR_PERSONA.UUID_PERSONA IS 'Identificador único de la tabla';
COMMENT ON COLUMN CUR_PERSONA.UUID_CIUDAD IS 'Identificador único de la tabla CAT_CIUDAD';
COMMENT ON COLUMN CUR_PERSONA.UUID_ESTADO IS 'Identificador único de la tabla CAT_ESTADO';
COMMENT ON COLUMN CUR_PERSONA.UUID_PAIS IS 'Identificador único de la tabla CAT_PAIS';
COMMENT ON COLUMN CUR_PERSONA.NOMBRE IS 'Nombre de la persona';
COMMENT ON COLUMN CUR_PERSONA.APELLIDO_PATERNO IS 'Apellido paterno de la persona';
COMMENT ON COLUMN CUR_PERSONA.APELLIDO_MATERNO IS 'Apellido materno de la persona';
COMMENT ON COLUMN CUR_PERSONA.TELEFONO IS 'Número telefónico';
COMMENT ON COLUMN CUR_PERSONA.EMAIL IS 'Correo electrónico de la persona';
COMMENT ON COLUMN CUR_PERSONA.FECHA_ALTA IS 'Fecha de alta de la persona';
COMMENT ON COLUMN CUR_PERSONA.VERIFICADO IS '0 = Si Verificado, 99 = No Verificado';
COMMENT ON COLUMN CUR_PERSONA.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CUR_PERSONA.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CUR_PERSONA.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CUR_PERSONA.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CUR_PERSONA.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CUR_PERSONA.NOTAS IS 'Observaciones adicionales del registro';
