ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CUR_TELEFONO_CLIENTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CUR_TELEFONO_CLIENTE (
  UUID_TELEFONO VARCHAR2(36) NOT NULL,
  UUID_CLIENTE VARCHAR2(36) NOT NULL,
  TELEFONO VARCHAR2(20) NOT NULL,
  ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
  FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
  CREADO_POR VARCHAR2(36) NOT NULL,
  FECHA_ACTUALIZACION DATE,
  ACTUALIZADO_POR VARCHAR2(36),
  NOTAS VARCHAR2(100),
  CONSTRAINT PK_CUR_TELEFONO_CLIENTE_UUID_TELEFONO PRIMARY KEY (UUID_TELEFONO),
  CONSTRAINT UK_CUR_TELEFONO_CLIENTE_CLIENTE_TELEFONO UNIQUE (UUID_CLIENTE, TELEFONO),
  CONSTRAINT CK_CUR_TELEFONO_CLIENTE_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);
COMMENT ON TABLE CUR_TELEFONO_CLIENTE IS 'Tabla que contiene los teléfonos de los Clientes';
COMMENT ON COLUMN CUR_TELEFONO_CLIENTE.UUID_TELEFONO IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CUR_TELEFONO_CLIENTE.UUID_CLIENTE IS 'Identificador único UUID de la tabla CUR_CLIENTE';
COMMENT ON COLUMN CUR_TELEFONO_CLIENTE.TELEFONO IS 'Número de teléfono del Cliente';
COMMENT ON COLUMN CUR_TELEFONO_CLIENTE.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CUR_TELEFONO_CLIENTE.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CUR_TELEFONO_CLIENTE.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CUR_TELEFONO_CLIENTE.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CUR_TELEFONO_CLIENTE.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CUR_TELEFONO_CLIENTE.NOTAS IS 'Observaciones adicionales del registro';
