ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CUR_DATO_FISCAL CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CUR_DATO_FISCAL (
    UUID_DATO_FISCAL VARCHAR2(36) NOT NULL,
    UUID_CLIENTE VARCHAR2(36) NOT NULL,
    UUID_TIPO_CLIENTE VARCHAR2(36) NOT NULL,
    RAZON_SOCIAL VARCHAR2(150) NOT NULL,
    RFC VARCHAR2(13) NOT NULL,
    CODIGO_POSTAL VARCHAR2(5) NOT NULL,
    USO_CFDI VARCHAR2(3) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_CUR_DATO_FISCAL_UUID_DATO_FISCAL PRIMARY KEY (UUID_DATO_FISCAL),
    CONSTRAINT CK_CUR_DATO_FISCAL_RFC CHECK (LENGTH(RFC) IN (12,13)),
    CONSTRAINT CK_CUR_DATO_FISCAL_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);

COMMENT ON TABLE CUR_DATO_FISCAL IS 'Tabla que almacena la información fiscal de los clientes para facturación CFDI 4.0';
COMMENT ON COLUMN CUR_DATO_FISCAL.UUID_DATO_FISCAL IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CUR_DATO_FISCAL.UUID_CLIENTE IS 'Identificador único UUID de la tabla CUR_CLIENTE';
COMMENT ON COLUMN CUR_DATO_FISCAL.UUID_TIPO_CLIENTE IS 'Identificador único UUID de la tabla CAT_TIPO_CLIENTE';
COMMENT ON COLUMN CUR_DATO_FISCAL.RAZON_SOCIAL IS 'Nombre o Denominación Social EXACTA como en la Constancia de Situación Fiscal';
COMMENT ON COLUMN CUR_DATO_FISCAL.RFC IS 'Registro Federal de Contribuyentes';
COMMENT ON COLUMN CUR_DATO_FISCAL.CODIGO_POSTAL IS 'Domicilio fiscal del cliente';
COMMENT ON COLUMN CUR_DATO_FISCAL.USO_CFDI IS 'Clave del uso del CFDI';
COMMENT ON COLUMN CUR_DATO_FISCAL.EMAIL IS 'Email del envío de la factura';
COMMENT ON COLUMN CUR_DATO_FISCAL.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CUR_DATO_FISCAL.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CUR_DATO_FISCAL.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CUR_DATO_FISCAL.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CUR_DATO_FISCAL.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CUR_DATO_FISCAL.NOTAS IS 'Observaciones adicionales del registro';
