ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CUR_PAGO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CUR_PAGO (
  UUID_PAGO VARCHAR2(36) NOT NULL,
  UUID_FACTURA VARCHAR2(36) NOT NULL,
  UUID_ESTADO_PAGO VARCHAR2(36) NOT NULL,
  MONTO NUMBER (16,2) NOT NULL,
  FECHA_PAGO DATE DEFAULT SYSDATE NOT NULL,
  ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
  FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
  CREADO_POR VARCHAR2(36) NOT NULL,
  FECHA_ACTUALIZACION DATE,
  ACTUALIZADO_POR VARCHAR2(36),
  NOTAS VARCHAR2(100),
  CONSTRAINT PK_CUR_PAGO_UUID_PAGO PRIMARY KEY (UUID_PAGO),
  CONSTRAINT CK_CUR_PAGO_MONTO CHECK (MONTO > 0),
  CONSTRAINT CK_CUR_PAGO_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);
COMMENT ON TABLE CUR_PAGO IS 'Tabla que contiene los Pagos Totales o Parciales de una Factura';
COMMENT ON COLUMN CUR_PAGO.UUID_PAGO IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CUR_PAGO.UUID_FACTURA IS 'Identificador único UUID de la tabla CUR_FACTURA';
COMMENT ON COLUMN CUR_PAGO.UUID_ESTADO_PAGO IS 'Identificador único UUID de la tabla CAT_ESTADO_PAGO';
COMMENT ON COLUMN CUR_PAGO.MONTO IS 'Monto del Pago de la Factura';
COMMENT ON COLUMN CUR_PAGO.FECHA_PAGO IS 'Fecha de Pago de la Factura';
COMMENT ON COLUMN CUR_PAGO.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CUR_PAGO.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CUR_PAGO.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CUR_PAGO.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CUR_PAGO.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CUR_PAGO.NOTAS IS 'Observaciones adicionales del registro';
