ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CUR_FACTURA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE CUR_FACTURA (
    UUID_FACTURA VARCHAR2(36) NOT NULL,
    UUID_CLIENTE VARCHAR2(36) NOT NULL,
    UUID_ESTADO_FACTURA VARCHAR2(36) NOT NULL,
    MONTO_TOTAL NUMBER(16,2) NOT NULL,
    FOLIO NUMBER(10,0) NOT NULL,
    ANIO NUMBER(4,0) NOT NULL,
    FECHA_FACTURA DATE DEFAULT SYSDATE NOT NULL,
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_CUR_FACTURA_UUID_FACTURA PRIMARY KEY (UUID_FACTURA),
    CONSTRAINT CK_CUR_FACTURA_MONTO_TOTAL CHECK (MONTO_TOTAL >= 0),
    CONSTRAINT UK_CUR_FACTURA_FOLIO_ANIO UNIQUE (FOLIO, ANIO),
    CONSTRAINT CK_CUR_FACTURA_FOLIO CHECK (FOLIO > 0),
    CONSTRAINT CK_CUR_FACTURA_ANIO CHECK (ANIO >= 2000),
    CONSTRAINT CK_CUR_FACTURA_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);

COMMENT ON TABLE CUR_FACTURA IS 'Tabla que contiene las facturas de los clientes';
COMMENT ON COLUMN CUR_FACTURA.UUID_FACTURA IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CUR_FACTURA.UUID_CLIENTE IS 'Identificador único UUID de la tabla CUR_CLIENTE';
COMMENT ON COLUMN CUR_FACTURA.UUID_ESTADO_FACTURA IS 'Identificador único UUID de la tabla CAT_ESTADO_FACTURA';
COMMENT ON COLUMN CUR_FACTURA.MONTO_TOTAL IS 'Monto total de la factura';
COMMENT ON COLUMN CUR_FACTURA.FOLIO IS 'Folio consecutivo por año';
COMMENT ON COLUMN CUR_FACTURA.ANIO IS 'Año de la factura';
COMMENT ON COLUMN CUR_FACTURA.FECHA_FACTURA IS 'Fecha de la factura';
COMMENT ON COLUMN CUR_FACTURA.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CUR_FACTURA.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CUR_FACTURA.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CUR_FACTURA.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CUR_FACTURA.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CUR_FACTURA.NOTAS IS 'Observaciones adicionales del registro';
