/*===========================
 TABLA DE CLIENTE
===========================*/
ALTER SESSION SET CURRENT_SCHEMA = CURSOJAVA;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CUR_CLIENTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTE_CLAVE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/

CREATE SEQUENCE SEQ_CLIENTE_CLAVE START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;

CREATE TABLE CUR_CLIENTE (
    UUID_CLIENTE VARCHAR2(36) NOT NULL,
    UUID_CIUDAD VARCHAR2(36) NOT NULL,
    UUID_ESTADO VARCHAR2(36) NOT NULL,
    UUID_PAIS VARCHAR2(36) NOT NULL,
    CLAVE VARCHAR2(15) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(50) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(50),
    EMAIL VARCHAR2(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    ESTATUS_REGISTRO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_CUR_CLIENTE_UUID_CLIENTE PRIMARY KEY (UUID_CLIENTE),
    CONSTRAINT UK_CUR_CLIENTE_CLAVE UNIQUE (CLAVE),
    CONSTRAINT UK_CUR_CLIENTE_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_CUR_CLIENTE_ESTATUS_REGISTRO CHECK (ESTATUS_REGISTRO IN (0, 99))
);
COMMENT ON TABLE CUR_CLIENTE IS 'Tabla que contiene la información del Cliente';
COMMENT ON COLUMN CUR_CLIENTE.UUID_CLIENTE IS 'Identificador único UUID de la tabla';
COMMENT ON COLUMN CUR_CLIENTE.UUID_CIUDAD IS 'Identificador único UUID de la tabla CAT_CIUDAD';
COMMENT ON COLUMN CUR_CLIENTE.UUID_ESTADO IS 'Identificador único UUID de la tabla CAT_ESTADO';
COMMENT ON COLUMN CUR_CLIENTE.UUID_PAIS IS 'Identificador único UUID de la tabla CAT_PAIS';
COMMENT ON COLUMN CUR_CLIENTE.CLAVE IS 'Clave del Cliente';
COMMENT ON COLUMN CUR_CLIENTE.NOMBRE IS 'Nombre del Cliente';
COMMENT ON COLUMN CUR_CLIENTE.APELLIDO_PATERNO IS 'Apellido Paterno del Cliente';
COMMENT ON COLUMN CUR_CLIENTE.APELLIDO_MATERNO IS 'Apellido Materno del Cliente';
COMMENT ON COLUMN CUR_CLIENTE.EMAIL IS 'Correo del cliente';
COMMENT ON COLUMN CUR_CLIENTE.FECHA_NACIMIENTO IS 'Fecha de Nacimiento del Cliente';
COMMENT ON COLUMN CUR_CLIENTE.ESTATUS_REGISTRO IS '0 = Activo, 99 = Inactivo';
COMMENT ON COLUMN CUR_CLIENTE.FECHA_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN CUR_CLIENTE.CREADO_POR IS 'Usuario creador del registro';
COMMENT ON COLUMN CUR_CLIENTE.FECHA_ACTUALIZACION IS 'Fecha de actualización del registro';
COMMENT ON COLUMN CUR_CLIENTE.ACTUALIZADO_POR IS 'Usuario que actualizó el registro';
COMMENT ON COLUMN CUR_CLIENTE.NOTAS IS 'Observaciones adicionales del registro';

CREATE OR REPLACE TRIGGER TRG_CLIENTE_CLAVE
BEFORE INSERT ON CUR_CLIENTE
FOR EACH ROW
BEGIN
    IF :NEW.CLAVE IS NULL THEN
       SELECT 'CLI-' || LPAD(SEQ_CLIENTE_CLAVE.NEXTVAL, 6, '0')
       INTO :NEW.CLAVE
       FROM DUAL;
    END IF;
END;
/
